project:
  type: book

book:
  title: "Sam Kestin describes 50 years in the Yiddish Theater"
  author: "Sam Kestin, translated by Stephanie Spielman"
  chapters:
    - index.qmd
    - chapters/01_1946-09-07.qmd
    - chapters/02_1946-09-19.qmd
    - chapters/03_1946-09-21.qmd
    - chapters/04_1946-09-25.qmd
    - chapters/05_1946-09-28.qmd
    - chapters/06_1946-10-03.qmd
    - chapters/07_1946-10-10.qmd

format: html

website:
  google-analytics: "G-WWFS41KSZH"