project:
  type: book

book:
  title: "Cheatsheet Book for Data Lab Training"
  author: "for now just me!"
  cover-image: ccdl-logo.png
  chapters:
    - index.qmd
    - baseR.qmd

format:
  html:
    theme: cosmo

