
name: Spell check qmd files

on:
  push:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.2.3

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: Rscript --vanilla -e "install.packages(c('spelling'), repos = c(CRAN = '$CRAN'))"

      - name: Run spell check
        id: spell_check_run
        run: |
          results=$(Rscript --vanilla "scripts/spell-check.R")
          echo "sp_chk_results=$results" >> $GITHUB_OUTPUT
          cat spell_check_errors.tsv

      - name: Archive spelling errors
        uses: actions/upload-artifact@v3
        with:
          name: spell-check-results
          path: spell_check_errors.tsv

      # If there are too many spelling errors, this will stop the workflow
      - name: Check spell check results - fail if too many errors
        if: ${{ steps.spell_check_run.outputs.sp_chk_results > 0 }}
        run: exit 1
